M48
; DRILL file {KiCad (6.0.4)} date Fri Apr 29 23:06:03 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-29T23:06:03+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.4062Y-6.4488
X3.6338Y-6.4488
T2
X2.6932Y-3.973
X2.6932Y-5.9415
X4.3468Y-3.973
X4.3468Y-5.9415
T0
M30
